//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPagosModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Liberaciones
    {
        public int Id { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Notas { get; set; }
        public string Num_Liberacion { get; set; }
    
        public virtual Tb_Requisiciones Tb_Requisiciones { get; set; }
    }
}
